.nh
.TH geteduroam-cli 1 "April 2026" "geteduroam-cli 0.14" "Geteduroam"

.SH NAME
geteduroam-notifcheck \- Checks if eduroam certificates are still validte


.SH SYNOPSIS
\fBgeteduroam-cli\fP [-h | --help]


.SH DESCRIPTION
\fBgeteduroam-notifcheck\fP checks if the eduroam connection profile are still valid. If they expire within ten days it will send a message via notify-send(1). It provides a systemd user service to automate this on a daily basis.


.SH OPTIONS
\fB-h\fP and \fB--help\fP display a basic help message and exit.
