.nh
.TH geteduroam-gui 1 "April 2026" "geteduroam-gui 0.14" "Geteduroam"

.SH NAME
geteduroam-gui \- GTK interface for the geteduroam utility


.SH SYNOPSIS
\fBgeteduroam-gui\fP [options]

.PP
\fBgeteduroam-gui\fP --help | -h | --version


.SH DESCRIPTION
\fBgeteduroam-gui\fP is a GTK interface to make eduroam connection profiles for NetworkManager. It requires a network connection, because it needs to authorize via MicroSoft to generate the eduroam certificates. \fBgeteduroam-gui\fP puts its files in \fI~/.local/share/geteduroam\fP\&.


.SH OPTIONS
\fB-h\fP and \fB--help\fP display a basic help message and exit.

.PP
\fB--version\fP print version number and exit.

.PP
\fB-d\fP and \fB--debug\fP enable debug mode.

.PP
\fB--gtk-args\fP arguments that get passed to GTK as a string, e.g. "--help". These flags are split on spaces.
