.nh
.TH geteduroam-cli 1 "April 2026" "geteduroam-cli 0.14" "Geteduroam"

.SH NAME
geteduroam-cli \- CLI interface for the geteduroam utility


.SH SYNOPSIS
\fBgeteduroam-cli\fP [options]

.PP
\fBgeteduroam-cli\fP --help | -h | --version


.SH DESCRIPTION
\fBgeteduroam-cli\fP is a CLI interface to make eduroam connection profiles for NetworkManager. It requires a network connection, because it needs to authorize via MicroSoft to generate the eduroam certificates. \fBgeteduroam-cli\fP puts its files in \fI~/.local/share/geteduroam\fP\&.


.SH OPTIONS
\fB-h\fP and \fB--help\fP display a basic help message and exit.

.PP
\fB--version\fP print version number and exit.

.PP
\fB-v\fP enable verbose mode.

.PP
\fB-d\fP and \fB--debug\fP enable debug mode.

.PP
\fB-l\fP \fI/path/to/file\fP and \fB--local\fP=\fI/path/to/file\fP the path to a local EAP metadata file. 

.PP
\fB-u\fP \fIurl\fP and \fB--url\fP=\fIurl\fP the URL where an EAP metadata file or Let's Wifi portal is hosted. 
